"""Reproduce the compact Lua Jie table from the locally pinned lunar-python 1.4.8.

Build-time tool only: Python and this vendor directory are never needed in game.
Run from anywhere: python tools/generate_calendar_data.py [--check]
No network is used. Data contain astronomical transitions, never birth profiles.
"""
import argparse
from datetime import datetime
from hashlib import sha256
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / 'vendor'
sys.path.insert(0, str(VENDOR))
from lunar_python import Solar
from lunar_python.util import LunarUtil

EPOCH = datetime(1900, 1, 1)
OUTPUT = ROOT / 'mod' / 'TenYearsNineGrid' / 'calendar_data.lua'


def generate():
    package = VENDOR / '_sources' / 'lunar_python-1.4.8.tar.gz'
    license_text = (VENDOR / 'lunar_python-1.4.8.dist-info' / 'licenses' / 'LICENSE').read_text(encoding='utf-8').strip()
    rows = []
    for year in range(1900, 2202):
        lunar = Solar.fromYmd(year, 7, 1).getLunar()
        table = lunar.getJieQiTable()
        current = []
        for key in lunar.JIE_QI_IN_USE[::2]:
            term = table[key]
            if term.getYear() != year:
                continue
            timestamp = int((datetime.fromisoformat(term.toYmdHms()) - EPOCH).total_seconds())
            exact = term.getLunar()
            current.append((timestamp, LunarUtil.getJiaZiIndex(exact.getYearInGanZhiExact()),
                            LunarUtil.getJiaZiIndex(exact.getMonthInGanZhiExact())))
        assert len(current) == 12, (year, len(current))
        rows.extend(sorted(current))
    assert len(rows) == 302 * 12
    assert all(left[0] < right[0] for left, right in zip(rows, rows[1:]))
    day_epoch = Solar.fromYmd(1900, 1, 1).getLunar().getDayInGanZhiExact2()
    header = f'''-- GENERATED by tools/generate_calendar_data.py; do not hand-edit.
-- Source: lunar-python 1.4.8, https://github.com/6tail/lunar-python
-- Source archive SHA256: {sha256(package.read_bytes()).hexdigest()}
-- License and upstream attribution are retained below.
-- Coverage: twelve Jie per Gregorian year, 1900 through 2201 inclusive.
-- Each row: {{Beijing wall seconds since 1900-01-01T00:00:00+08:00,
--            exact year JiaZi index, exact month JiaZi index}}, indices 0..59.
-- Rows switch pillars inclusively at that second. No DST or solar-time shift.
-- Terms in annual order: 小寒 立春 惊蛰 清明 立夏 芒种 小暑 立秋 白露 寒露 立冬 大雪.
--[[
{license_text}
]]
return {{
  format_version=1,
  library="lunar-python1.4.8",
  source_url="https://github.com/6tail/lunar-python",
  source_sha256="{sha256(package.read_bytes()).hexdigest()}",
  calculation_timezone="UTC+08:00",
  first_year=1900,last_year=2201,
  epoch={{1900,1,1}},day_epoch_index={LunarUtil.getJiaZiIndex(day_epoch)},
  terms={{
'''
    return header + ''.join('    {%d,%d,%d},\n' % row for row in rows) + '  }\n}\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Compare with committed generated data without writing.')
    args = parser.parse_args()
    source = generate()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != source:
            raise SystemExit('FAIL: calendar_data.lua differs from pinned source generation.')
        print(f'PASS: reproducible calendar_data.lua ({len(source.encode("utf-8"))} bytes, 3624 transitions)')
    else:
        OUTPUT.write_text(source, encoding='utf-8', newline='\n')
        print(f'Generated {OUTPUT.name}: {len(source.encode("utf-8"))} bytes, 3624 transitions')


if __name__ == '__main__':
    main()
